- name: Install AWS CLI, Kops, Kubectl
  hosts: local
  vars_files:
    - vars/kops-vars.yml
  tasks:
    - name: Install unzip, curl, wget
      become: true
      package:
        name: "{{ item }}"
        state: present
      loop:
        - unzip
        - curl
        - wget

    - name: Install AWS CLI v2
      become: true
      shell: |
        curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
        unzip awscliv2.zip
        sudo ./aws/install

    - name: Install kubectl
      become: true
      shell: |
        curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
        install -o root -g root -m 0755 kubectl /usr/local/bin/kubectl

    - name: Install kops
      become: true
      shell: |
        curl -LO https://github.com/kubernetes/kops/releases/latest/download/kops-linux-amd64
        chmod +x kops-linux-amd64
        mv kops-linux-amd64 /usr/local/bin/kops
