- name: Create Kubernetes Cluster via Kops
  hosts: local
  vars_files:
    - vars/kops-vars.yml
  tasks:
    - name: Ensure SSH public key exists (generate from linux.pem if needed)
      ansible.builtin.shell: |
        if [ ! -f ~/.ssh/linux.pub ] && [ -f ~/.ssh/linux.pem ]; then
          ssh-keygen -y -f ~/.ssh/linux.pem > ~/.ssh/linux.pub
        fi
      args:
        executable: /bin/bash

    - name: Export KOPS_STATE_STORE
      ansible.builtin.shell: |
        export KOPS_STATE_STORE={{ kops_state_store }}
      environment:
        KOPS_STATE_STORE: "{{ kops_state_store }}"

    - name: Create cluster configuration
      ansible.builtin.shell: |
        kops create cluster \
          --name={{ kops_cluster_name }} \
          --zones={{ availability_zones[0] }},{{ availability_zones[1] }} \
          --node-count={{ node_count }} \
          --node-size=t3.medium \
          --master-size=t3.medium \
          --ssh-public-key={{ ssh_key_path }} \
          --cloud=aws \
          --yes
      environment:
        KOPS_STATE_STORE: "{{ kops_state_store }}"

    - name: Validate cluster
      shell: |
        kops validate cluster --name {{ kops_cluster_name }} --wait 10m
      environment:
        KOPS_STATE_STORE: "{{ kops_state_store }}"

